config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  resources :comments, only: [:create, :edit, :update, :destroy]

  resources :articles do
    resources :comments, only: [:create]
  end

  resources :articles, except: [:index]
  root "home#index"
  get '/articles', to: 'articles#index', as: 'user_root'
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :article
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_article
  before_action :require_login

  def show
  end

  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.build(comment_params)
    @comment.user = current_user

    if @comment.save
      redirect_to @article, notice: 'Comment was successfully created.'
    else
      render 'articles/show'
    end
  end

  def destroy
    @comment = @article.comments.find(params[:id])

    if @comment.user == current_user
      @comment.destroy
      redirect_to @article, notice: 'Comment was successfully destroyed.'
    else
      redirect_to @article, alert: 'You are not authorized to delete this comment.'
    end
  end

  private

  def set_article
    @article = Article.find(params[:article_id])
  end

  def comment_params
    params.require(:comment).permit(:content)
  end

  def require_login
    unless current_user
      redirect_to login_path, alert: 'You must be logged in to perform this action.'
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<div id="<%= dom_id comment %>">
</div>
<p><strong><%= comment.user.email %>:</strong> <%= comment.content %></p>

app/views/comments/_form.html.erb
<%= form_with(model: comment) do |form| %>
  <% if comment.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
        <% comment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
      <div class="field">
          <%= form.label :content, class:"form-label" %>
          <%= form.comment :content, class:"form-control" %>
      </div>
  </div>


  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<%= form_with(model: [ @article, @comment ], local: true) do |form| %>
  <%= form.text_area :content, placeholder: "Escribe tu comentario..." %>
  <%= form.submit "Guardar Cambios" %>
<% end %>

app/views/comments/index.html.erb
<%= link_to "New comment", new_comment_path %>
<p style="color: green"><%= notice %></p>

<h1>Comments</h1>

<div id="comments">
  <% @comments.each do |comment| %>
    <%= render comment %>
    <p>
      <%= link_to "Show this comment", comment %>
    </p>
  <% end %>
</div>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render "form", comment: @comment %>

<br>

<div>
  <%= link_to "Back to comments", comments_path %>
</div>

app/views/comments/show.html.erb
<p><strong><%= @comment.user.email %>:</strong> <%= @comment.content %></p>
<p><%= link_to 'Editar', edit_article_comment_path(@article, @comment) %></p>
<p><%= link_to 'Eliminar', article_comment_path(@article, @comment), method: :delete, data: { confirm: '¿Estás seguro?' } %></p>